version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "amazon-dynamodb-react-axios"
s3_bucket = ""
s3_prefix = "amazon-dynamodb-react-axios"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
